platform: linux/amd64

clone:
  git:
    image: bash
    commands:
      - echo "test"
      - uname
      - env

pipeline:
  build:
    image: bash
    commands:
      - echo "HELLO WORLD3"
      - uname
      - nix run nixpkgs#neofetch
      - nix build '.#go-karma-bot'
